name: Ruby

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      shell: bash
      run:  |
        docker compose run --rm tdd rake test
      env:
        RACK_ENV: test
