name: Ruby

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: bundle install
      shell: bash
      run:  |
        docker compose -f docker-compose-ci.yaml up tdd -d
        docker compose exec tdd bundle install
    - name: Run Rubocop
      shell: bash
      run:  |
        docker compose exec tdd bundle exec rubocop --parallel
    - name: Run tests
      shell: bash
      run:  |
        docker compose exec tdd rake test
      env:
        RACK_ENV: test
